# Generated by Django 4.2.30 on 2026-07-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[("umrah", "Umrah Package"), ("hajj", "Hajj Package")],
                        default="umrah",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration_days", models.IntegerField(default=15)),
                (
                    "agent_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wholesale price charged to the agent (PKR)",
                        max_digits=10,
                    ),
                ),
                (
                    "suggested_resale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Suggested price agent charges client",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated agent commission margin",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("total_seats", models.PositiveIntegerField(default=30)),
                ("booked_seats", models.PositiveIntegerField(default=0)),
                ("makkah_hotel_name", models.CharField(blank=True, max_length=200)),
                ("makkah_hotel_distance", models.CharField(blank=True, max_length=100)),
                ("madinah_hotel_name", models.CharField(blank=True, max_length=200)),
                (
                    "madinah_hotel_distance",
                    models.CharField(blank=True, max_length=100),
                ),
                ("images", models.JSONField(blank=True, default=list, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Package",
                "verbose_name_plural": "Agent Packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentTicketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(max_length=30, unique=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket"),
                            ("group", "Group"),
                            ("umrah", "Umrah"),
                            ("hajj", "Hajj"),
                        ],
                        default="ticket",
                        max_length=10,
                    ),
                ),
                (
                    "baggage_weight_kg",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("traveler_contact_email", models.EmailField(max_length=254)),
                ("agent_contact_email", models.EmailField(max_length=254)),
                ("total_fare", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hold", "On Hold"),
                            ("paid", "Paid"),
                            ("paid_pending", "Payment Pending"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="hold",
                        max_length=20,
                    ),
                ),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                ("pnr", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agent_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="airline_ticketing.agentpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Ticket Order",
                "verbose_name_plural": "Agent Ticket Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "iata_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IATA 2-letter airline code, e.g. PK, SV, EK",
                        max_length=10,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="airlines/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AirlineFlightInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_city", models.CharField(max_length=100)),
                ("destination_city", models.CharField(max_length=100)),
                ("departure_time", models.CharField(default="00:00 AM", max_length=50)),
                ("arrival_time", models.CharField(default="00:00 AM", max_length=50)),
                ("total_seats", models.PositiveIntegerField(default=0)),
                ("booked_seats", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_inventory",
                        to="airline_ticketing.airline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Inventory",
                "verbose_name_plural": "Flight Inventories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderPassenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passenger_type",
                    models.CharField(
                        choices=[
                            ("adult", "Adult"),
                            ("child", "Child"),
                            ("infant", "Infant"),
                        ],
                        default="adult",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=10)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("passport_number", models.CharField(max_length=50)),
                ("passport_issue_date", models.DateField()),
                ("passport_expiry_date", models.DateField()),
                (
                    "allotted_ticket_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="airline_ticketing.agentticketorder",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GroupFarePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_group_size",
                    models.PositiveIntegerField(
                        help_text="Minimum seats to qualify for group fare (e.g. 10)"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (%)"),
                            ("flat", "Flat Amount (PKR)"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount percentage (0-100) or flat amount in PKR",
                        max_digits=10,
                    ),
                ),
                (
                    "baggage_weight_kg",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Baggage allowance tier this policy applies to (e.g. 20, 30, 40)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flight_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_policies",
                        to="airline_ticketing.airlineflightinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Fare Policy",
                "verbose_name_plural": "Group Fare Policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BaggageFareTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_kg",
                    models.PositiveIntegerField(
                        help_text="Baggage weight in KG, e.g. 7, 20, 30, 40"
                    ),
                ),
                (
                    "fare",
                    models.DecimalField(
                        decimal_places=2, help_text="Fare in PKR", max_digits=10
                    ),
                ),
                (
                    "flight_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baggage_tiers",
                        to="airline_ticketing.airlineflightinventory",
                    ),
                ),
            ],
            options={
                "ordering": ["weight_kg"],
            },
        ),
        migrations.AddField(
            model_name="agentticketorder",
            name="flight_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="airline_ticketing.airlineflightinventory",
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="airline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_packages",
                to="airline_ticketing.airline",
            ),
        ),
    ]
