# Generated by Django 4.2.30 on 2026-07-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0002_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentpackage",
            name="adult_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Wholesale adult price (PKR)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="child_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Wholesale child price (PKR)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="departure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="hotels",
            field=models.ManyToManyField(
                blank=True, related_name="agent_packages", to="airline_ticketing.hotel"
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="infant_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Wholesale infant price (PKR)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentticketorder",
            name="selected_hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="airline_ticketing.hotel",
            ),
        ),
        migrations.AddField(
            model_name="agentticketorder",
            name="selected_sharing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sharing", "Sharing"),
                    ("quad", "Quad"),
                    ("triple", "Triple"),
                    ("double", "Double"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
