# Generated by Django 4.2.30 on 2026-07-25 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "airline_ticketing",
            "0003_agentpackage_adult_price_agentpackage_child_price_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("origin_city", models.CharField(max_length=100)),
                ("destination_city", models.CharField(max_length=100)),
                ("is_round_trip", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="has_meal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="return_arrival_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="return_departure_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="return_route_type",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("via", "Via Connection")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="return_via_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="route_type",
            field=models.CharField(
                choices=[("direct", "Direct"), ("via", "Via Connection")],
                default="direct",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="trip_type",
            field=models.CharField(
                choices=[("oneway", "One Way"), ("return", "Return")],
                default="return",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="via_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="SeatAdjustmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_field",
                    models.CharField(default="total_seats", max_length=20),
                ),
                ("old_value", models.IntegerField()),
                ("new_value", models.IntegerField()),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agent_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_adjustments",
                        to="airline_ticketing.agentpackage",
                    ),
                ),
                (
                    "flight_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_adjustments",
                        to="airline_ticketing.airlineflightinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat Adjustment Log",
                "verbose_name_plural": "Seat Adjustment Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_packages",
                to="airline_ticketing.sector",
            ),
        ),
        migrations.AddField(
            model_name="airlineflightinventory",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flights",
                to="airline_ticketing.sector",
            ),
        ),
    ]
