# Generated by Django 4.2.30 on 2026-07-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0004_sector_airlineflightinventory_has_meal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentticketorder",
            name="agent_phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="agentticketorder",
            name="traveler_contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="orderpassenger",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderpassenger",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="orderpassenger",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="orderpassenger",
            name="nationality",
            field=models.CharField(blank=True, default="Pakistan", max_length=100),
        ),
        migrations.AlterField(
            model_name="orderpassenger",
            name="passport_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderpassenger",
            name="passport_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderpassenger",
            name="passport_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="orderpassenger",
            name="title",
            field=models.CharField(blank=True, default="Mr", max_length=10),
        ),
    ]
