# Generated by Django 4.2.30 on 2026-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0005_agentticketorder_agent_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentpackage",
            name="price_double",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package price per person in Double Room (PKR)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="price_quad",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package price per person in Quad Room (PKR)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="price_sharing",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package price per person in Sharing Room (PKR)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="price_triple",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package price per person in Triple Room (PKR)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
