# Generated by Django 4.2.30 on 2026-07-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "airline_ticketing",
            "0006_agentpackage_price_double_agentpackage_price_quad_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Ibrahim Khalil Road, Hijra Road",
                max_length=255,
            ),
        ),
    ]
