# Generated by Django 4.2.30 on 2026-07-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0007_hotel_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=150)),
                ("account_title", models.CharField(max_length=150)),
                ("account_number", models.CharField(max_length=100)),
                (
                    "bank_logo",
                    models.ImageField(blank=True, null=True, upload_to="banks/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "ordering": ["bank_name"],
            },
        ),
    ]
