# Generated by Django 4.2.30 on 2026-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0008_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpassenger",
            name="passport_image",
            field=models.FileField(
                blank=True,
                help_text="Uploaded passport document image/copy",
                null=True,
                upload_to="passports/",
            ),
        ),
    ]
