# Generated by Django 4.2.30 on 2026-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0009_orderpassenger_passport_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentpackage",
            name="flight_name",
            field=models.CharField(
                blank=True, default="Saudi Airlines", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="flight_route",
            field=models.CharField(
                blank=True, default="KHI - JED - MED - KHI", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="flight_route_type",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct Flight"), ("via", "Via Flight")],
                default="direct",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="includes_meal",
            field=models.BooleanField(
                default=True, help_text="Meal Included: Yes / No"
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="meal_detail",
            field=models.CharField(
                blank=True, default="Full Board", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="transport_type",
            field=models.CharField(
                blank=True, default="Sharing", max_length=100, null=True
            ),
        ),
    ]
