# Generated by Django 4.2.30 on 2026-07-31 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "airline_ticketing",
            "0010_agentpackage_flight_name_agentpackage_flight_route_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="groupfarepolicy",
            name="airline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="standalone_group_policies",
                to="airline_ticketing.airline",
            ),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="airline_name_custom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="arrival_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="available_seats",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="base_fare",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="departure_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="departure_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="destination_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="group_fare_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override calculated net group fare directly",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="has_meal",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="return_arrival_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="return_baggage_weight_kg",
            field=models.PositiveIntegerField(
                default=30, help_text="Return Baggage allowance in KG"
            ),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="return_departure_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="route_type",
            field=models.CharField(default="direct", max_length=20),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="total_seats",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="trip_type",
            field=models.CharField(default="oneway", max_length=20),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="via_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="airlineflightinventory",
            name="trip_type",
            field=models.CharField(
                choices=[
                    ("oneway", "One Way"),
                    ("return", "Return / Round Trip"),
                    ("multicity", "Multi City"),
                ],
                default="return",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="groupfarepolicy",
            name="baggage_weight_kg",
            field=models.PositiveIntegerField(
                default=30, help_text="Outbound Baggage allowance in KG"
            ),
        ),
        migrations.AlterField(
            model_name="groupfarepolicy",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage (0-100) or flat amount in PKR",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="groupfarepolicy",
            name="flight_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_policies",
                to="airline_ticketing.airlineflightinventory",
            ),
        ),
        migrations.AlterField(
            model_name="groupfarepolicy",
            name="min_group_size",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Minimum seats to qualify for group fare (e.g. 10)",
            ),
        ),
    ]
