# Generated by Django 4.2.30 on 2026-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0011_groupfarepolicy_airline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "Economy Class / Building"),
                    ("3star", "3 Star Hotel"),
                    ("4star", "4 Star Hotel"),
                    ("5star", "5 Star Hotel"),
                ],
                default="economy",
                max_length=20,
            ),
        ),
    ]
