# Generated by Django 4.2.30 on 2026-07-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0012_hotel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "Economy Class"),
                    ("economy_plus", "Economy Plus"),
                    ("1star", "1 Star Hotel"),
                    ("2star", "2 Star Hotel"),
                    ("3star", "3 Star Hotel"),
                    ("4star", "4 Star Hotel"),
                    ("5star", "5 Star Hotel"),
                ],
                default="economy",
                max_length=20,
            ),
        ),
    ]
