# Generated by Django 4.2.30 on 2026-07-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0013_alter_hotel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentticketorder",
            name="group_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="airline_ticketing.groupfarepolicy",
            ),
        ),
    ]
