# Generated by Django 4.2.30 on 2026-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0014_agentticketorder_group_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentticketorder",
            name="admin_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="agentticketorder",
            name="original_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="is_round_trip",
            field=models.BooleanField(default=False),
        ),
    ]
