# Generated by Django 4.2.30 on 2026-08-03 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0015_agentticketorder_admin_discount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentHajjPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="agent_hajj/logos/"
                    ),
                ),
                ("duration_days", models.PositiveIntegerField()),
                ("price_quad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_triple", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_double", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_sharing",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hajj_operator_name", models.CharField(max_length=200)),
                ("license_number", models.CharField(max_length=100)),
                ("saudi_registration_number", models.CharField(max_length=100)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("includes_meal", models.BooleanField(default=True)),
                (
                    "meal_detail",
                    models.CharField(
                        blank=True,
                        default="Full Board Buffet",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "airline_name",
                    models.CharField(
                        blank=True, default="Saudi Airlines", max_length=150, null=True
                    ),
                ),
                (
                    "airline_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="agent_hajj/airlines/"
                    ),
                ),
                (
                    "flight_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "flight_route",
                    models.CharField(
                        blank=True,
                        default="KHI - JED - MED - KHI",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "makkah_hotel_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "makkah_hotel_distance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "madinah_hotel_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "madinah_hotel_distance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("total_seats", models.PositiveIntegerField()),
                ("available_seats", models.PositiveIntegerField()),
                ("images", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Hajj Package",
                "verbose_name_plural": "Agent Hajj Packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentHajjAccommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[("makkah", "Makkah"), ("madinah", "Madinah")],
                        max_length=20,
                    ),
                ),
                (
                    "manual_hotel_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "manual_hotel_distance",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("nights", models.PositiveIntegerField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "agent_hajj_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="airline_ticketing.agenthajjpackage",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_hajj_stays",
                        to="airline_ticketing.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Hajj Accommodation",
                "verbose_name_plural": "Agent Hajj Accommodations",
                "ordering": ["order"],
            },
        ),
    ]
