# Generated by Django 4.2.30 on 2026-08-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0016_agenthajjpackage_agenthajjaccommodation"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentpackage",
            name="madinah_nights",
            field=models.PositiveIntegerField(
                default=7, help_text="Number of nights in Madinah"
            ),
        ),
        migrations.AddField(
            model_name="agentpackage",
            name="makkah_nights",
            field=models.PositiveIntegerField(
                default=7, help_text="Number of nights in Makkah"
            ),
        ),
    ]
