# Generated by Django 4.2.30 on 2026-08-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0017_agentpackage_madinah_nights_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentticketorder",
            name="agent_hajj_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="airline_ticketing.agenthajjpackage",
            ),
        ),
    ]
