# Generated by Django 4.2.30 on 2026-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0018_agentticketorder_agent_hajj_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentticketorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("hold", "On Hold"),
                    ("paid", "Paid"),
                    ("paid_pending", "Payment Pending"),
                    ("ticketed", "Ticketed"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="hold",
                max_length=20,
            ),
        ),
    ]
