# Generated by Django 4.2.30 on 2026-08-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0019_add_ticketed_confirmed_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentpackage",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="umrah_packages/covers/"
            ),
        ),
    ]
