# Generated by Django 4.2.30 on 2026-08-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0020_agentpackage_cover_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="airlineflightinventory",
            name="sectors_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed 4 going and 4 coming sectors breakdown",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="sectors_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed 4 going and 4 coming sectors breakdown",
                null=True,
            ),
        ),
    ]
