# Generated by Django 4.2.30 on 2026-08-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0021_airlineflightinventory_sectors_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airlineflightinventory",
            name="sectors_data",
        ),
        migrations.RemoveField(
            model_name="groupfarepolicy",
            name="sectors_data",
        ),
    ]
