# Generated by Django 4.2.30 on 2026-08-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "airline_ticketing",
            "0022_remove_airlineflightinventory_sectors_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="groupfarepolicy",
            name="route_sectors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured leg/sector details: flight_no, dep/arr city, date, time",
                null=True,
            ),
        ),
    ]
