# Generated by Django 4.2.30 on 2026-08-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0023_groupfarepolicy_route_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="airlineflightinventory",
            name="sectors_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Per-leg details: [{"route":"LYP-SHJ","flight_no":"SV-734","dep_time":"03:30 AM","arr_time":"07:15 AM"}, ...]',
            ),
        ),
    ]
