# Generated by Django 4.2.30 on 2026-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0024_airlineflightinventory_sectors_data_v2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupfarepolicy",
            name="base_fare",
        ),
        migrations.RemoveField(
            model_name="groupfarepolicy",
            name="group_fare_override",
        ),
        migrations.RemoveField(
            model_name="groupfarepolicy",
            name="route_sectors",
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="sectors_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed 4 going and 4 coming sectors breakdown",
                null=True,
            ),
        ),
    ]
