# Generated by Django 4.2.30 on 2026-08-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0025_remove_groupfarepolicy_base_fare_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupfarepolicy",
            name="base_fare",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Base/Net fare in PKR",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupfarepolicy",
            name="group_fare_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net Group Fare override in PKR",
                max_digits=12,
                null=True,
            ),
        ),
    ]
