# Generated by Django 4.2.30 on 2026-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0026_groupfarepolicy_base_fare_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenthajjaccommodation",
            name="check_in_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agenthajjaccommodation",
            name="check_out_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
