# Generated by Django 4.2 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0027_agenthajjaccommodation_check_in_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentpackage",
            name="sectors_data",
            field=models.JSONField(blank=True, default=dict, help_text="Detailed flight legs breakdown with departure/arrival times & flight numbers", null=True),
        ),
    ]
