# Generated by Django 6.0.8 on 2026-08-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0028_agentpackage_sectors_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentpackage",
            name="baggage_detail",
            field=models.CharField(
                blank=True,
                default="30 KG",
                help_text="Baggage allowance (e.g. 30 KG, 20 KG, 2x23 KG)",
                max_length=100,
                null=True,
            ),
        ),
    ]
