# Generated by Django 4.2.30 on 2026-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="adults_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="children_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="discount_applied",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="sharing_category",
            field=models.CharField(
                blank=True, default="Quad", max_length=50, null=True
            ),
        ),
    ]
