# Generated by Django 4.2.30 on 2026-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_adults_count_booking_children_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="infants_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="selected_addons",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
