# Generated by Django 4.2.30 on 2026-07-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_infants_count_booking_selected_addons"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="pnr",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
