# Generated by Django 4.2.30 on 2026-07-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline_name", models.CharField(max_length=100)),
                ("flight_number", models.CharField(max_length=50)),
                ("departure_city", models.CharField(max_length=100)),
                ("destination_city", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="flights/"),
                ),
                (
                    "static_image_name",
                    models.CharField(
                        blank=True,
                        default="flights_banner.png",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlightTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy Class"),
                            ("business", "Business Class"),
                            ("first", "First Class"),
                        ],
                        default="economy",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("baggage_allowance", models.CharField(default="30 KG", max_length=50)),
                (
                    "refund_policy",
                    models.CharField(default="Refundable with fee", max_length=100),
                ),
                ("seats_available", models.PositiveIntegerField(default=10)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="flights.flight",
                    ),
                ),
            ],
        ),
    ]
