# Generated by Django 4.2.30 on 2026-07-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_flight_flightticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirlinePartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon_class",
                    models.CharField(default="fa-solid fa-plane", max_length=50),
                ),
                (
                    "description",
                    models.CharField(default="Official Partner", max_length=150),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
