# Generated by Django 4.2.30 on 2026-07-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_airlinepartner"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightTicketOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline_name", models.CharField(max_length=100)),
                (
                    "airline_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "airline_logo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("flight_number", models.CharField(max_length=50)),
                ("departure_city", models.CharField(max_length=100)),
                (
                    "departure_airport_code",
                    models.CharField(default="KHI", max_length=10),
                ),
                ("destination_city", models.CharField(max_length=100)),
                (
                    "destination_airport_code",
                    models.CharField(default="JED", max_length=10),
                ),
                (
                    "departure_time_str",
                    models.CharField(default="03:30 AM", max_length=50),
                ),
                (
                    "arrival_time_str",
                    models.CharField(default="06:45 AM", max_length=50),
                ),
                ("duration_str", models.CharField(default="4h 15m", max_length=50)),
                (
                    "flight_type",
                    models.CharField(
                        choices=[
                            ("direct", "Non-Stop (Direct)"),
                            ("one_stop", "1 Stop"),
                            ("two_stop", "2 Stops"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "ticket_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy Class"),
                            ("premium_economy", "Premium Economy"),
                            ("business", "Business Class"),
                            ("first", "First Class"),
                        ],
                        default="economy",
                        max_length=30,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("baggage_checkin", models.CharField(default="30 kg", max_length=50)),
                ("baggage_hand", models.CharField(default="7 kg", max_length=50)),
                ("is_refundable", models.BooleanField(default=True)),
                (
                    "cancellation_fee",
                    models.DecimalField(
                        decimal_places=2, default=15000.0, max_digits=10
                    ),
                ),
                ("total_seats", models.IntegerField(default=50)),
                ("available_seats", models.IntegerField(default=50)),
                ("is_popular", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
