# Generated by Django 4.2.30 on 2026-07-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_flightticketoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightticketoffer",
            name="price_20kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="flightticketoffer",
            name="price_30kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="flightticketoffer",
            name="price_40kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
