# Generated by Django 4.2.30 on 2026-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0005_flightticketoffer_price_20kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightticketoffer",
            name="has_meal",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="flightticketoffer",
            name="meal_service",
            field=models.CharField(default="Meal Included", max_length=100),
        ),
        migrations.AddField(
            model_name="flightticketoffer",
            name="price_handcarry",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="flightticketoffer",
            name="via_routes",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
