# Generated by Django 4.2.30 on 2026-08-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0008_flightticketoffer_price_23kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightticketoffer",
            name="trip_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct_oneway", "Direct One-Way"),
                    ("direct_roundtrip", "Direct Round-Trip"),
                    ("oneway_via", "One-Way Via"),
                    ("roundtrip_via", "Round-Trip Via"),
                    ("multicity", "Multi-City"),
                ],
                default="direct_oneway",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FlightSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("airline_name", models.CharField(max_length=100)),
                ("flight_number", models.CharField(blank=True, max_length=50)),
                ("departure_city", models.CharField(max_length=100)),
                ("departure_airport_code", models.CharField(blank=True, max_length=10)),
                ("arrival_city", models.CharField(max_length=100)),
                ("arrival_airport_code", models.CharField(blank=True, max_length=10)),
                ("departure_datetime", models.DateTimeField()),
                ("arrival_datetime", models.DateTimeField()),
                (
                    "flight_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="flights.flightticketoffer",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
