# Generated by Django 4.2.30 on 2026-07-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visaapplication",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="visa_type",
            field=models.CharField(
                blank=True, default="Tourist / Visitor Visa", max_length=100, null=True
            ),
        ),
    ]
