# Generated by Django 4.2.30 on 2026-07-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa", "0002_visaapplication_additional_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                (
                    "visa_type",
                    models.CharField(default="Tourist / Visitor Visa", max_length=100),
                ),
                (
                    "processing_time",
                    models.CharField(default="3 to 5 Working Days", max_length=100),
                ),
                (
                    "stay_validity",
                    models.CharField(default="90 Days Stay", max_length=100),
                ),
                (
                    "visa_validity",
                    models.CharField(default="1 Year Validity", max_length=100),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Entry"),
                            ("multiple", "Multiple Entry"),
                        ],
                        default="multiple",
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "required_documents",
                    models.TextField(
                        default="Passport Copy (6 Months Validity), Passport Size Photo with White Background, CNIC Copy"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("flag_icon", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "banner_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
