# Generated by Django 4.2.30 on 2026-08-08 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("visa", "0003_visapackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="visaapplication",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="visa_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="visa.visapackage",
            ),
        ),
        migrations.AddField(
            model_name="visapackage",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="visa_covers/"),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="passport_number",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visa_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
