# Generated by Django 4.2.30 on 2026-08-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa", "0004_visaapplication_address_visaapplication_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visapackage",
            name="countries_included",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="visapackage",
            name="is_multi_country",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visapackage",
            name="tour_destinations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
