# Generated by Django 4.2.30 on 2026-08-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa", "0005_visapackage_countries_included_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visapackage",
            name="flyer_document",
            field=models.FileField(blank=True, null=True, upload_to="visa_flyers/"),
        ),
        migrations.AddField(
            model_name="visapackage",
            name="group_name",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="visapackage",
            name="tower_hotel_details",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
