# Generated by Django 4.2.30 on 2026-07-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platformreview",
            options={
                "ordering": ["-is_featured", "-created_at"],
                "verbose_name": "Platform Review",
                "verbose_name_plural": "Platform Reviews",
            },
        ),
        migrations.AddField(
            model_name="platformreview",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Pin this review to appear first in the carousel",
            ),
        ),
        migrations.AddField(
            model_name="platformreview",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("none", "Text Only"),
                    ("image", "Image Review"),
                    ("video", "Video Review"),
                    ("youtube", "YouTube Embed"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="platformreview",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Reviewer photo or trip photo",
                null=True,
                upload_to="reviews/photos/",
            ),
        ),
        migrations.AddField(
            model_name="platformreview",
            name="reviewer_title",
            field=models.CharField(
                blank=True,
                help_text="e.g. Hajj Pilgrim 2024, CEO at Al-Noor Travels",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="platformreview",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="MP4 video testimonial file",
                null=True,
                upload_to="reviews/videos/",
            ),
        ),
        migrations.AddField(
            model_name="platformreview",
            name="youtube_url",
            field=models.CharField(
                blank=True,
                help_text="Full YouTube URL e.g. https://www.youtube.com/watch?v=xxxx",
                max_length=200,
                null=True,
            ),
        ),
    ]
