# Generated by Django 4.2.30 on 2026-07-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_platformreview_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformreview",
            name="media_type",
        ),
        migrations.RemoveField(
            model_name="platformreview",
            name="video_file",
        ),
        migrations.RemoveField(
            model_name="platformreview",
            name="youtube_url",
        ),
    ]
