# Generated by Django 4.2.30 on 2026-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_remove_platformreview_media_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("video", "Video / Media"),
                            ("meeting", "Meeting / Event"),
                            ("milestone", "Milestone / Award"),
                        ],
                        default="milestone",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="achievements/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to YouTube, Vimeo, etc. (optional)",
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
