# Generated by Django 4.2.30 on 2026-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_loginhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.FloatField(default=5.0),
        ),
    ]
