# Generated by Django 4.2.30 on 2026-07-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_partner",
            field=models.BooleanField(default=False),
        ),
    ]
