# Generated by Django 4.2.30 on 2026-07-16 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_address_user_is_verified_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("commission", "Commission Earned"),
                            ("payment", "Payment Received"),
                            ("refund", "Refund Issued"),
                            ("adjustment", "Manual Adjustment"),
                            ("penalty", "Penalty / Deduction"),
                            ("advance", "Advance Payment"),
                            ("other", "Other"),
                        ],
                        default="commission",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Booking ID, invoice number, etc.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role": "agent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
