# Generated by Django 4.2.30 on 2026-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_agent_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminCustomBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=250)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("umrah", "Umrah Package"),
                            ("hajj", "Hajj Package"),
                            ("visa", "Visa Department"),
                            ("ticket", "Flight Ticket"),
                            ("general", "General Agency Expense"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("income", "Agency Income / Bill"),
                            ("expense", "Agency Expense / Supplier Cost"),
                        ],
                        default="expense",
                        max_length=10,
                    ),
                ),
                (
                    "vendor_client_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
