# Generated by Django 4.2.30 on 2026-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_admincustombill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentledger",
            name="category",
            field=models.CharField(
                choices=[
                    ("commission", "Commission Earned"),
                    ("payment", "Payment Received"),
                    ("refund", "Refund Issued"),
                    ("adjustment", "Manual Adjustment"),
                    ("penalty", "Penalty / Deduction"),
                    ("advance", "Advance Payment"),
                    ("ticket_purchase", "Ticket Purchase"),
                    ("other", "Other"),
                ],
                default="commission",
                max_length=20,
            ),
        ),
    ]
