# Generated by Django 4.2.30 on 2026-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_agentledger_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_id_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="id_card_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
