# Generated by Django 4.2.30 on 2026-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_agent_id_number_user_id_card_issued_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=150)),
                ("account_title", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=100)),
                ("iban", models.CharField(blank=True, max_length=100, null=True)),
                ("branch_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("swift_code", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
