# Generated by Django 4.2.30 on 2026-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_companybankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentledger",
            name="running_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
