# Generated by Django 4.2.30 on 2026-07-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_agentledger_running_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Feedback"),
                            ("ticket", "Ticket Booking Issue"),
                            ("wallet", "Wallet & Payment Inquiry"),
                            ("package", "Pilgrimage / Package Query"),
                            ("bug", "Portal Bug / Improvement"),
                            ("other", "Other Topic"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=250)),
                ("rating", models.IntegerField(default=5)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_reply", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role": "agent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
