# Generated by Django 4.2.30 on 2026-07-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_agentfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDepartmentContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=150)),
                (
                    "contact_person_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Department Contact",
                "verbose_name_plural": "Company Department Contacts",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
