# Generated by Django 4.2.30 on 2026-07-31 06:01

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_fix_superuser_roles"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
