# Generated by Django 4.2.30 on 2026-07-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_custompackageinquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="airline",
            field=models.CharField(
                blank=True, default="Saudi Airlines", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="airline_logo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="available_seats",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="package",
            name="flight_routes",
            field=models.CharField(
                blank=True, default="KHI - JED - MED - KHI", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="luggage_weight",
            field=models.CharField(
                blank=True, default="20 kg + 7 kg Hand Carry", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="madinah_hotel_distance",
            field=models.CharField(
                blank=True,
                default="150m from Prophet's Mosque",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="madinah_hotel_name",
            field=models.CharField(
                blank=True, default="Pullman Zamzam Madinah", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="makkah_hotel_distance",
            field=models.CharField(
                blank=True, default="350m from Haram", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="makkah_hotel_name",
            field=models.CharField(
                blank=True, default="Anjum Hotel Makkah", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="total_seats",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="package",
            name="duration_days",
            field=models.IntegerField(default=15),
        ),
    ]
