# Generated by Django 4.2.30 on 2026-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_package_airline_package_airline_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="package",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="package",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="price_child",
            field=models.DecimalField(
                decimal_places=2, default=180000.0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="price_double",
            field=models.DecimalField(
                decimal_places=2, default=320000.0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="price_quad",
            field=models.DecimalField(
                decimal_places=2, default=245000.0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="price_triple",
            field=models.DecimalField(
                decimal_places=2, default=275000.0, max_digits=10
            ),
        ),
    ]
