# Generated by Django 4.2.30 on 2026-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "packages",
            "0004_package_discount_amount_package_discount_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="addons",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="madinah_hotel_images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="makkah_hotel_images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="price_infant",
            field=models.DecimalField(decimal_places=2, default=65000.0, max_digits=10),
        ),
    ]
