# Generated by Django 4.2.30 on 2026-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0005_package_addons_package_madinah_hotel_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="price_sharing",
            field=models.DecimalField(
                decimal_places=2, default=210000.0, max_digits=10
            ),
        ),
    ]
