# Generated by Django 4.2.30 on 2026-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0006_package_price_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="flight_route_type",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct Flight"), ("via", "Via Flight")],
                default="direct",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="includes_meal",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="package",
            name="meal_detail",
            field=models.CharField(
                blank=True, default="Full Board", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="transport_type",
            field=models.CharField(
                blank=True, default="Sharing", max_length=100, null=True
            ),
        ),
    ]
