# Generated by Django 4.2.30 on 2026-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0007_package_flight_route_type_package_includes_meal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="departure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="flight_dates",
            field=models.CharField(
                blank=True,
                default="15 Aug 2026 - 30 Aug 2026",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
