# Generated by Django 4.2.30 on 2026-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0008_package_departure_date_package_flight_dates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="packages/covers/"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
