# Generated by Django 4.2.30 on 2026-08-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0015_agentticketorder_admin_discount_and_more"),
        ("packages", "0009_package_cover_image_package_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="HajjPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="hajj/logos/"),
                ),
                ("duration_days", models.PositiveIntegerField()),
                ("price_quad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_triple", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_double", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_sharing",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hajj_operator_name", models.CharField(max_length=200)),
                ("license_number", models.CharField(max_length=100)),
                ("saudi_registration_number", models.CharField(max_length=100)),
                ("total_seats", models.PositiveIntegerField()),
                ("available_seats", models.PositiveIntegerField()),
                ("images", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HajjAccommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[("makkah", "Makkah"), ("madinah", "Madinah")],
                        max_length=20,
                    ),
                ),
                ("nights", models.PositiveIntegerField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "hajj_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="packages.hajjpackage",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hajj_stays",
                        to="airline_ticketing.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
