# Generated by Django 4.2.30 on 2026-08-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0010_hajjpackage_hajjaccommodation"),
    ]

    operations = [
        migrations.AddField(
            model_name="hajjpackage",
            name="airline_logo",
            field=models.ImageField(blank=True, null=True, upload_to="hajj/airlines/"),
        ),
        migrations.AddField(
            model_name="hajjpackage",
            name="airline_name",
            field=models.CharField(
                blank=True, default="Saudi Airlines", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="hajjpackage",
            name="departure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hajjpackage",
            name="flight_dates",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="hajjpackage",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
