# Generated by Django 4.2.30 on 2026-08-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline_ticketing", "0015_agentticketorder_admin_discount_and_more"),
        ("packages", "0011_hajjpackage_airline_logo_hajjpackage_airline_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hajjaccommodation",
            name="distance_manual",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hajjaccommodation",
            name="hotel_name_manual",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="madinah_nights",
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="makkah_nights",
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name="hajjaccommodation",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hajj_stays",
                to="airline_ticketing.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="hajjaccommodation",
            name="nights",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
