# Generated by Django 4.2.30 on 2026-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0012_hajjaccommodation_distance_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hajjpackage",
            name="hijri_dates",
            field=models.CharField(
                blank=True,
                default="01 - 25 Dhul-Hijjah 1447 AH",
                max_length=150,
                null=True,
            ),
        ),
    ]
