# Generated by Django 4.2.30 on 2026-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0013_hajjpackage_hijri_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="hajjpackage",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="hajj_packages/covers/"
            ),
        ),
    ]
