# Generated by Django 4.2.30 on 2026-08-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0014_hajjpackage_cover_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="price_child_no_bed",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=120000.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="price_child_with_bed",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=180000.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="sectors_data",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="flight_route_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct", "Direct Flight (Round Trip)"),
                    ("via", "Round Trip (Via Flight)"),
                    ("multi_city", "Multi City (Via Flight)"),
                ],
                default="direct",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price_child",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=180000.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price_double",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=320000.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price_infant",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=65000.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price_quad",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=245000.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price_sharing",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=210000.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price_triple",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=275000.0, max_digits=10, null=True
            ),
        ),
    ]
