# Generated by Django 4.2.30 on 2026-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0015_package_price_child_no_bed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hajjaccommodation",
            name="check_in_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hajjaccommodation",
            name="check_out_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
