# Generated by Django 4.2.30 on 2026-08-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0016_hajjaccommodation_check_in_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hajjpackage",
            name="madinah_hotel_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hajjpackage",
            name="madinah_nights",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hajjpackage",
            name="makkah_hotel_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hajjpackage",
            name="makkah_nights",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
