# Generated by Django 4.2.30 on 2026-07-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="brand-orange",
                        help_text="Tailwind color class prefix e.g. emerald, blue, brand-orange",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/covers/"),
                ),
                (
                    "static_cover",
                    models.CharField(
                        blank=True,
                        help_text="Filename of static image inside static/images/ e.g. blog_hajj.png",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary shown on list cards",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Full article body (supports HTML / markdown)"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(default="Golden Star Team", max_length=100),
                ),
                (
                    "author_avatar",
                    models.CharField(
                        blank=True,
                        help_text="Filename of static avatar image e.g. avatar_team.png",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "read_time",
                    models.PositiveIntegerField(
                        default=5, help_text="Estimated read time in minutes"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show in hero/featured slot on blog list",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0, editable=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
